languageCode = "en"
languageName = "English"
weight = 1
title = "dracuxan"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  logo = "img/dragon.png"
  description = "A vault to Day-0 of my projects and more"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "dracuxan"
  image = "img/dragon.png"
  headline = "Yet another CS undergrad trying to build yet another reliable software."
  bio = "Yet another CS undergrad trying to build yet another reliable software."
   links = [
     { github = "https://github.com/dracuxan" },
     # { x-twitter = "https://x.com/dracuxan" },
     { linkedin = "https://linkedin.com/in/nisargkhodke" }
   ]
